//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by rasterizer.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_rasterizerTYPE              130
#define ID_WINDOW_MANAGER               131
#define IDD_VERTEX_FMT_DIALOG           310
#define ID_VIEW_PROPERTIESWND           310
#define IDC_PROPERTIES_BAR              311
#define IDC_PROPERTIES_SPLITTER         312
#define IDR_3D_TOOLBAR                  313
#define IDC_FRAMES_PANE                 313
#define IDC_FACES_PANE                  314
#define IDD_SCENE                       315
#define IDC_MATERIALS_PANE              315
#define IDC_DRAG_HOVER                  316
#define IDD_FACES                       317
#define IDC_FACE_COLWND                 317
#define IDC_COLOURWND_TIMER             318
#define IDD_MATERIALS                   319
#define IDD_LIGHT                       320
#define IDC_LIGHT_PANE                  321
#define IDC_LIGHT_COLWND                322
#define IDC_FACE_TITLE                  323
#define IDC_LIGHT_TITLE                 324
#define IDC_MATERIAL_TITLE              325
#define IDC_SCENE_TITLE                 326
#define IDR_3D_TOOLBAR_32BPP            327
#define IDC_POS_CHECK                   1002
#define IDC_NORM_CHECK                  1003
#define IDC_TEX_CHECK                   1004
#define IDC_BUMP_CHECK                  1005
#define IDC_COL_CHECK                   1006
#define IDC_TEX_COMBO                   1007
#define IDC_BUMP_COMBO                  1008
#define IDC_TEX_GEN_CHECK               1009
#define IDC_COL_GEN_CHECK               1010
#define IDC_BUMP_GEN_CHECK              1011
#define IDC_NORM_GEN_CHECK              1012
#define IDC_COLOUR                      1014
#define IDC_MAT_TEXTURE_BUTTON          1017
#define IDC_MAT_SHININESS_EDIT          1018
#define IDC_MAT_COL_CHECK               1019
#define IDC_MAT_DIFFUSE_COLOUR          1020
#define IDC_MAT_AMBIENT_COLOUR          1021
#define IDC_MAT_SPECULAR_COLOUR         1022
#define IDC_MAT_TEX_CHECK               1023
#define IDC_MAT_BUMP_CHECK              1024
#define IDC_MAT_BUMP_BUTTON             1026
#define IDC_MAT_CUBIC_CHECK             1027
#define IDC_MAT_CUBIC_BUTTON            1029
#define IDC_OPACITY_EDIT                1030
#define IDC_OPACITY_SPIN                1031
#define IDC_MAT_DIFFUSE                 1032
#define IDC_MAT_AMBIENT                 1033
#define IDC_MAT_SHININESS               1034
#define IDC_MAT_SPECULAR                1035
#define IDC_TITLE                       1036
#define IDC_UV_COMBO                    1037
#define IDC_SCENE_TREE                  1038
#define IDC_OPACITY_SLIDER              1039
#define IDC_OPACITY_STATIC              1040
#define IDC_FACES_EDIT                  1041
#define IDC_FACES_SPIN                  1042
#define IDC_UV_U_EDIT                   1043
#define IDC_VERTEX_COMBO                1044
#define IDC_INDEX_STATIC                1045
#define IDC_VERTEX_STATIC               1046
#define IDC_XYZ_X_EDIT                  1047
#define IDC_XYZ_Y_EDIT                  1048
#define IDC_XYZ_Z_EDIT                  1049
#define IDC_XYZ_COMBO                   1051
#define IDC_UV_V_EDIT                   1054
#define IDC_NORM_COMBO                  1055
#define IDC_XYZ_EDGE                    1058
#define IDC_UV_EDGE                     1059
#define IDC_SPOT_EDGE                   1060
#define IDC_COLOUR_STATIC               1061
#define IDC_RANGE_STATIC                1062
#define IDC_RANGE_EDIT                  1063
#define IDC_ATTEN_EDGE                  1064
#define IDC_ATTEN_COMBO                 1065
#define IDC_ATTEN_EDIT                  1066
#define IDC_COLOUR_EDGE                 1067
#define IDC_COLOUR_COMBO                1068
#define IDC_SPOT_COMBO                  1069
#define IDC_SPOT_EDIT                   1071
#define IDC_RANGE_COMBO                 1072
#define IDC_RANGE_ADD                   1073
#define IDC_RANGE_FROM_EDIT             1075
#define IDC_RANGE_TO_EDIT               1076
#define IDC_RANGE_INCLUSIVETO_EDIT      1076
#define IDC_IMAGE_EDGE                  1077
#define IDC_IMAGE_COMBO                 1078
#define IDC_RANGE_DEL                   1080
#define IDC_RANGE_FROM_SPIN             1081
#define IDC_RANGE_INCLUSIVETO_SPIN      1082
#define IDC_COLOUR_CHECK                1083
#define IDC_IMAGE_CHECK                 1084
#define IDC_IMAGE_BROWSE                1085
#define IDC_SHININESS_STATIC            1086
#define IDC_SHININESS_EDIT              1087
#define IDC_UV_SET                      1088
#define IDC_RANGE_ALL                   1089
#define IDC_IMAGE_STATIC                1090
#define IDC_MAT_TEXTURE_STATIC          1091
#define IDC_MAT_BUMP_STATIC             1092
#define IDC_MAT_CUBIC_STATIC            1093
#define IDC_IMAGE_PATH                  1094
#define IDC_MAT_DIFFUSE_CHECK           1095
#define IDC_MAT_SHININESS_CHECK         1096
#define IDC_EFFECT_COMBO                1097
#define ID_CAMERA_FRONT                 32772
#define ID_CAMERA_BACK                  32773
#define ID_CAMERA_LEFT                  32774
#define ID_CAMERA_RIGHT                 32775
#define ID_CAMERA_ABOVE                 32776
#define ID_CAMERA_BELOW                 32777
#define ID_TRANSLATE_SCALE_TOOL         32778
#define ID_DEPTH_TOOL                   32779
#define ID_ROTATE_TOOL                  32780
#define ID_CANCEL                       32783
#define ID_CAMERA_DEPTH_TOOL            32786
#define ID_CAMERA_TRANSLATE_TOOL        32787
#define ID_CAMERA_ROTATE_TOOL           32788
#define ID_FPS                          32790
#define ID_SCENE_NEWWINDOW              32791
#define ID_CAMERA_FRONT_NEW             32792
#define ID_CAMERA_BACK_NEW              32793
#define ID_CAMERA_LEFT_NEW              32794
#define ID_CAMERA_RIGHT_NEW             32795
#define ID_CAMERA_ABOVE_NEW             32796
#define ID_CAMERA_BELOW_NEW             32797
#define ID_NEWWINDOW_DUPLICATE          32798
#define ID_CAMERA_DUPLICATE_NEW         32799
#define ID_SCENE_RENDER                 32800
#define ID_RENDER_MODELS                32801
#define ID_MODEL_RENDER                 32802
#define ID_RENDER_LIGHTS                32803
#define ID_LIGHT_RENDER                 32804
#define ID_SCENE_CREATELIGHT            32805
#define ID_SPOT_LIGHT_CREATE            32809
#define ID_POINT_LIGHT_CREATE           32810
#define ID_DIRECTIONAL_LIGHT_CREATE     32811
#define ID_OBJ_IMPORT                   32812
#define ID_DELETE                       32813
#define ID_RENDER_SHADOWS               32815
#define ID_SHADOW_RENDER                32816

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        328
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           327
#endif
#endif
